# Generated by Django 3.0.6 on 2020-06-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='memebers',
            new_name='members',
        ),
    ]
